### ISSUE TITLE
Install Failed

### ISSUE THREAD

**Issue by RoberMac** [Danielhiversen/PyXiaomiGateway#10]
```
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-tog0d3fl/pyCrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-b94068hq-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-tog0d3fl/pyCrypto/
```

Maybe switch to PyCryptodome?

**Comment by syssi** [comment]
Could you post the complete error message? There should be mentioned a log file somewhere. The log file contains a hint which system dependency is missing. libssl-dev for example or build-essential are candidates.

**Comment by Danielhiversen** [comment]
Are you using the library with Home Assistant?

**Comment by RoberMac** [comment]
Yes. I use it with Home Assistant.

Due to `pyCryto` is deprecated, it should not be used.

I fork your library and change [`pyCryto` to `PyCryptodome`](https://github.com/RoberMac/PyXiaomiGateway/commit/71a26b19b687b4a0174582c4e30a6dce0405ad3c)  , then issue was solved

**Comment by Danielhiversen** [comment]
The problem is that some of the other libraries in HA uses pyCrypto, and I do not think you can have both pyCrypto and PyCryptodome installed at the same time.

But great you solved your problem.
