### ISSUE TITLE
Install 0.10.0 on docker (synology)

### ISSUE THREAD

**Issue by antibill51** [Danielhiversen/PyXiaomiGateway#100]
Hi. I'm running home assistant on a synology ds415+ with docker and homeassistant/home-assistant:latest.
Is it possible updating PyXiaomiGateway to 0.10.0 and how? 

Thanks you.

**Comment by Danielhiversen** [comment]
Latest version of HA is now using 0.11.0

**Comment by antibill51** [comment]
Cool, but with HA 0.79.3 I still not view vibration sensors... Is there something to do?
I remake docker container but no change.. 
Thanks

**Comment by syssi** [comment]
The HA support of the vibration sensor isn't merged yet.
