### ISSUE TITLE
Unsupportee device Found

### ISSUE THREAD

**Issue by callejo79** [Danielhiversen/PyXiaomiGateway#101]
I have HASSIO with last update 78.2 with Raspberry Pi 3 id model WXKG02LM

xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b286acn01', 'sid': '158d00027c1f64', 'short_id': 47399, 'data': '{"voltage":3185}'}
2018-09-22 23:19:38 WARNING (MainThread) [homeassistant.setup] Setup of xiaomi_aqara is taking over 10 seconds.

**Comment by syssi** [comment]
Fixed by #108 and will be introduced into Home Assistant soon.
