### ISSUE TITLE
Unsupported device, vibration, tilt 

### ISSUE THREAD

**Issue by henninne** [Danielhiversen/PyXiaomiGateway#102]
Hi,

I run Home assistant 0.77.3 with the Xiaomi gateway connected. I now just added the new Aqara smart sensor with vibration, tilt sensors, but received this when I restarted HA. 

Unsupported device:
provide the following data: 
{'cmd': 'read_ack', 'model': 'vibration', 'sid': '158d0002a921f6', 'short_id': 23451, 'data': '{"voltage":3065}'}

**Comment by syssi** [comment]
This library already supports the vibration sensor already. Just the Home Assistant support isn't merged yet:

home-assistant/home-assistant#16422
