### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by wonderfullay** [Danielhiversen/PyXiaomiGateway#106]
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'data': '{"voltage":3055}', 'short_id': 34675, 'cmd': 'read_ack', 'sid': '158d000213864a', 'model': 'remote.b1acn01'}

**Comment by syssi** [comment]
Fixed by #108 and will be introduced into Home Assistant soon.
