### ISSUE TITLE
Unsupported device found (for the new Aqara Vibration sensor)

### ISSUE THREAD

**Issue by aherrang** [Danielhiversen/PyXiaomiGateway#110]
Hi,

I got this error:

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'data': '{"voltage":3005}', 'sid': '158d0002a21af8', 'model': 'vibration', 'short_id': 26036}

Thanks,

**Comment by 0obuwawao0** [comment]
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'sid': '158d0002a8ce34', 'model': 'vibration.aq1', 'params': [{'battery_voltage': 3055}], 'cmd': 'read_rsp'}
