### ISSUE TITLE
Aqara wireless mini switch not appearing as entity in HASSIO

### ISSUE THREAD

**Issue by zzzdrkarlzzz** [Danielhiversen/PyXiaomiGateway#115]
Aqara wireless mini switch WXKG11LM  is connected in Mihome app but not appearing as an entity in HASSIO 0.79.3

Gateway v3

data: {'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001ef6140', 'short_id': 8778, 'data': '{"voltage":3145}'}

**Comment by syssi** [comment]
This device should work with HA 0.81.
