### ISSUE TITLE
Another unsopported vibration device. 

### ISSUE THREAD

**Issue by andreaontheweb** [Danielhiversen/PyXiaomiGateway#116]
Hello I got the following error. 
It seems different from the other issues already closed for a similar vibration sensor. 
PS I already installed the 11.1 version of this library. 
Thanks 

 found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'sid': '158d0002a9226a', 'data': '{"voltage":3115}', 'model': 'vibration', 'cmd': 'read_ack', 'short_id': 30521}

**Comment by syssi** [comment]
Please use the "dev" branch of Home Assistant, too.

**Comment by andreaontheweb** [comment]
tryed to install the homeassistant-0.81.0.dev0 but problem persist....

**Comment by syssi** [comment]
Which gateway do you own? The vibration sensor works fine with my lumi v3 gateway.

**Comment by andreaontheweb** [comment]
My gateway is the lumi v3 too.
It recognize the vibration sensor and work properly.

**Comment by andreaontheweb** [comment]
I mean using the mihome app..

**Comment by andreaontheweb** [comment]
Don't know
pip3 install --upgrade homeassistant gives me:
Requirement already up-to-date: homeassistant in /usr/local/lib/python3.5/dist-packages (0.81.0.dev0)

and:
hass --version
0.81.0.dev0

**Comment by syssi** [comment]
Did you enter the virtualenv beforehand?

**Comment by Ener-G** [comment]
Yes. The other products (Small switch, door sensor, etc.) works fine

**Comment by Ener-G** [comment]
This is the message:
[xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'data': '{"voltage":3135}', 'model': 'remote.b1acn01', 'sid': '158d0001ef60ad', 'short_id': 46944, 'cmd': 'read_ack'}

**Comment by andreaontheweb** [comment]
ok that was my bad.
I forgot i was on a python virtual environment.
Now it works.
