### ISSUE TITLE
Aqara Smart Wireless Switch / new international version with "hold" action

### ISSUE THREAD

**Issue by loly-girl** [Danielhiversen/PyXiaomiGateway#118]
{'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001e792b8', 'short_id': 1212, 'data': '{"voltage":3055}'}

**Comment by silvanverschuur** [comment]
I think I've got the same device. The button has support for single press, double press and long press.

{'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0002132a4b', 'short_id': 2589, 'data': '{"voltage":3165}'}

**Comment by elect0nik** [comment]
me too.  {'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001ef86d7', 'short_id': 61851, 'data': '{"voltage":3115}'}

**Comment by jussbba** [comment]
{'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001e89157', 'short_id': 26708, 'data': '{"voltage":3085}'}

**Comment by donrico1988** [comment]
{'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001ef8950', 'short_id': 9992, 'data': '{"voltage":3045}'}

**Comment by bengizmo** [comment]
{'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001ef628a', 'short_id': 54475, 'data': '{"voltage":3085}'}

**Comment by Apipa169** [comment]
{'cmd': 'read_ack', 'model': 'remote.b286acn01', 'sid': '158d0002829eef', 'short_id': 22828, 'data': '{"voltage":3055}'}

I've tried to add this device several times via the Mi Home app as a different type of switch (there are a few).

**Comment by heartkingz** [comment]
Two aqara smart switches with the same problem: 

{'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001ef39f5', 'short_id': 30302, 'data': '{"voltage":3055}'}

{'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001e7a115', 'short_id': 19855, 'data': '{"voltage":3055}'}

**Comment by fcollingwood** [comment]
I have this issue too: {'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001e79089', 'short_id': 2100, 'data': '{"voltage":3165}'}

**Comment by jrkoiter** [comment]
Same here: {'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d00021346e8', 'short_id': 25639, 'data': '{"voltage":3135}'}

**Comment by jrkoiter** [comment]
I got this working by using latest source of Home Assistant. That uses latest version of this library, and also has some code changes to accommodate this switch.

**Comment by heartkingz** [comment]
> I got this working by using latest source of Home Assistant. That uses latest version of this library, and also has some code changes to accommodate this switch.

You mean by updating to 0.80.3? Mine still flagged as unsupported in the log.

**Comment by WilliamNL** [comment]
0.80.3 didn't change a thing unfortunately.

**Comment by fcollingwood** [comment]
Has been added here in line 235:

https://github.com/Danielhiversen/PyXiaomiGateway/blob/master/xiaomi_gateway/__init__.py

**Comment by fcollingwood** [comment]
Right. Had to add the file referenced above to config/custom_components/xiaomi_gateway, and add an edited version of xiaomi_aqara.py to config/custom_components (Edited to reference the above file) and also add an edited version of xiaomi_aqara.py to config/custom_components/binary_sensor (Edited to add the new switch model name).

It is now detected, but I am not seeing any events from it. This was supposedly fixed in #108 but has not been

**Comment by jrkoiter** [comment]
The required changes are not yet part of a release. I updated the following three files to latest git revision:
```
components/binary_sensor/xiaomi_aqara.py
components/remote/xiaomi_miio.py
components/xiaomi_aqara.py
```
I"ll wait with upgrading HA until this is part of the release.

**Comment by syssi** [comment]
The device support will be part of HA 0.81.
