### ISSUE TITLE
Xiaomi Wireless WIFI Socket vibrate state since HA 0.80.0

### ISSUE THREAD

**Issue by galoz11** [Danielhiversen/PyXiaomiGateway#119]
![soc](https://user-images.githubusercontent.com/40101938/46913085-42099f80-cf8f-11e8-83b1-7964466ef35f.gif)
Home Assistant release with the issue:
HA 0.80.0

Last working Home Assistant release:
0.79.3

Operating environment (Hass.io/Docker/Windows/etc.):
raspberry pi virtual env with HA

Component/platform:
Xiaomi Gateway (Aqara)

Description of problem:
Xiaomi Wireless WIFI Socket vibrate state since HA 0.80.0.
i have two pi machine, the one that was upgrade to 0.80.0 make the power switch vibrate
and change states rapidly.
nothing in the logs.
(i shut down 0.80.0 machine and try the 0.79.3 and the problem gone)

Problem-relevant configuration.yaml entries and (fill out even if it seems unimportant):
no problem there

Additional information:

**Comment by PaulAnnekov** [comment]
No need to open the same issue twice in different projects. Closing in favor of https://github.com/home-assistant/home-assistant/issues/17422.
