### ISSUE TITLE
Home Assistant initialize failed

### ISSUE THREAD

**Issue by iamsuperark** [Danielhiversen/PyXiaomiGateway#12]
After I upgrade the Home Assistant to 0.53.1, i found my Xiaomi gateway failed to initialized. the start up log show bellow:

[homeassistant.setup] Not initializing xiaomi because could not install dependency https://github.com/Danielhiversen/PyXiaomiGateway/archive/0.3.2.zip#PyXiaomiGateway==0.3.2 

May I how to fix this issue? thanks.

**Comment by iamsuperark** [comment]
seems this is in the 
/srv/homeassistant/lib/python3.4/site-packages/homeassistant/components/xiaomi.py

Is it due to the Home Assistant Upgrade from 0.52? everything else is fine.

**Comment by iamsuperark** [comment]
homebridge@0.4.28 is upgraded as well.

**Comment by Danielhiversen** [comment]
You should open a issue at Home Assistant.

**Comment by iamsuperark** [comment]
may i manually install this package to my pi3 to fulfill this requirement ? i can download this zip file in my pc.
