### ISSUE TITLE
Aqara Wall Switch not discovered

### ISSUE THREAD

**Issue by MichaelZanetti** [Danielhiversen/PyXiaomiGateway#123]
I have the Wireless Wall Switch which, on the package, is labelled as WXKG02LM and it seems to be undiscovered:

{'cmd': 'read_ack', 'model': 'remote.b286acn01', 'sid': '158d00027c2aa6', 'short_id': 1728, 'data': '{"voltage":3055}'}

Using Home Assistant 0.80.2

**Comment by Danielhiversen** [comment]
#124
