### ISSUE TITLE
Unsupported device found! Xiaomi 

### ISSUE THREAD

**Issue by INTELBB** [Danielhiversen/PyXiaomiGateway#124]
Just recieved new Aqara wall switch (double button).
Here is the log. 

{'cmd': 'read_ack', 'model': 'remote.b286acn01', 'sid': '158d00027c125b', 'short_id': 62785, 'data': '{"voltage":3155}'}

**Comment by craig3050** [comment]
Same for me, new aqara sticky buttons 
{'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001ef86d3', 'short_id': 32345, 'data': '{"voltage":3215}'}

**Comment by ncsmits** [comment]
I have the same problem with the new Aqara switch (double, LN). Seems to be a new model of the switches. It appears to be a 'DuplexButton862' now, see: https://www.npmjs.com/package/homebridge-mi-aqara

**Comment by Dinges28** [comment]
Also for me:
{'data': '{"voltage":3055}', 'short_id': 60150, 'model': 'remote.b286acn01', 'cmd': 'read_ack', 'sid': '158d00027axxxx'}

**Comment by jyz0501** [comment]
Log Details (ERROR)
Fri Oct 26 2018 21:23:04 GMT+0800 (中国标准时间)

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b186acn01', 'sid': '158d00028f7ea4', 'short_id': 34686, 'data': '{"voltage":3125}'}

**Comment by Danielhiversen** [comment]
#118
