### ISSUE TITLE
unsupported device found

### ISSUE THREAD

**Issue by DerDa180** [Danielhiversen/PyXiaomiGateway#125]
Hey There, 
I have an issue with an Aqara Wireless Button (Single Button WXKG03LM).

I got the following error message at log: 

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b186acn01', 'sid': '158d000283f0d9', 'short_id': 1933, 'data': '{"voltage":3035}'}

I've already tried to use the following workaround: https://github.com/Danielhiversen/PyXiaomiGateway/issues/97

I replaced the model ID's with the ID from the error message but it didn't work...

I'm using Homeassistant 0.80.3

thanks in advance 
cheers

**Comment by jyz0501** [comment]
I have the same problem
Log Details (ERROR)
Wed Oct 24 2018 09:33:22 GMT+0800 (中国标准时间)

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_rsp', 'model': 'remote.b286acn01', 'sid': '158d00028f8a4c', 'params': [{'battery_voltage': 3065}]}

**Comment by Danielhiversen** [comment]
#124
