### ISSUE TITLE
Unsupported device found

### ISSUE THREAD

**Issue by camadio** [Danielhiversen/PyXiaomiGateway#126]
Hello, I got this message in my log:

2018-10-27 02:04:05 ERROR (Thread-5) [xiaomi_gateway] 
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: 
{'model': 'remote.b1acn01', 'short_id': 8685, 'cmd': 'read_ack', 'data': '{"voltage":3185}', 'sid': '158d0001ef8729'}

**Comment by syssi** [comment]
Please update HA. Version 0.81 is required.
