### ISSUE TITLE
Unsupported device found - Aquara Wireless Mini Switch

### ISSUE THREAD

**Issue by fbsdmon** [Danielhiversen/PyXiaomiGateway#127]
My HA threw the following error:
ERROR (Thread-10) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'model': 'remote.b1acn01', 'cmd': 'read_ack', 'short_id': 56173, 'sid': '158d0001ef56e9', 'data': '{"voltage":3215}'}#033[0m

I've introduced a Aquara Wireles Mini Switch to my Mi Gateway, which is apparently still not supported by HA.
Here is the item in question: https://www.aliexpress.com/item/Original-Xiaomi-Aqara-Smart-Wireless-Switch-Key-Intelligent-Application-Remote-Control-ZigBee-wireless-for-mi-home/32845804530.html

Can you extend the code to support this device? how can I help?

**Comment by PaulAnnekov** [comment]
What version of Home Assistant do you have? This issue was fixed in HA 0.81.0.

**Comment by slother** [comment]
@PaulAnnekov updating to latest fixed the problem, thanks.
