### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by soggypete** [Danielhiversen/PyXiaomiGateway#128]
Have already integrated many buttons to my HA setup with no issues.

Tried adding 2 buttons this evening and getting the above error.

Running hassio 0.80.3

data: {'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001ef6702', 'short_id': 12086, 'data': '{"voltage":3055}'}

AND

data: {'cmd': 'read_ack', 'model': 'remote.b286acn01', 'sid': '158d00027c0b1b', 'short_id': 13258, 'data': '{"voltage":3175}'}

**Comment by syssi** [comment]
Please update to HA 0.81.
