### ISSUE TITLE
Unsupported device found! mode: vibration

### ISSUE THREAD

**Issue by cofw2005** [Danielhiversen/PyXiaomiGateway#132]
Hello,

I see such note in the error log, I just added a new aqara vibration sensor to the gateway, after restart of homeassistant I cannot find the entity and see this note:
Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'model': 'vibration', 'cmd': 'read_ack', 'data': '{"voltage":3155}', 'short_id': 11837, 'sid': '158d0002b126fc'}

P.S. in the Xiaomi Aqara page, it says Vibration sensor is supported. Thank you!

**Comment by syssi** [comment]
Plesse update Home Assistent!
