### ISSUE TITLE
Unsupported device found! Please create an issue

### ISSUE THREAD

**Issue by Francisk0** [Danielhiversen/PyXiaomiGateway#133]
**Home Assistant release with the issue (if applicable):**

**Last working Home Assistant release (if known):**
0.75.3

**PyXiaomiGateway library version (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**
Docker in Synology

**Traceback (if applicable):**
```

```

**Description of the bug:**
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'vibration', 'sid': '158d0002a8cead', 'short_id': 21031, 'data': '{"voltage":3015}'}

**Comment by syssi** [comment]
Please update HA!
