### ISSUE TITLE
The device with sid xxx isn’t supported of the used gateway firmware. Please update the gateway firmware if possible! This is the only way the issue can be solved.

### ISSUE THREAD

**Issue by wmnl25** [Danielhiversen/PyXiaomiGateway#143]
See https://community.home-assistant.io/t/ikea-tradfri-controlled-by-xiaomi-gateway/92745/5

> The device with sid b57fffe361xxx isn’t supported of the used gateway firmware. Please update the gateway firmware if possible! This is the only way the issue can be solved.

GW firmware version is 1.4.1_164.0158. No updates available.

Seems that some (newer?) IKEA devices are not recognized correctly (for example an Ikea Warm White 1000lm bulb purchased a couple of days ago).

Should we wait for an gateway firmware update or is this something that can be fixed in the code?

**Comment by Danielhiversen** [comment]
Yes, you have to wait for a new firmware that supports the ikea bulb

**Comment by Caboz** [comment]
Realy? The IKEA bulbs work perfectly with the Xiaomi GW. Home Assistant just does not recognize them. I do not understand what is the problem with the firmware.

**Comment by Danielhiversen** [comment]
The current firmware does not expose the IKEA bulbs to the API.

**Comment by MrAlex1124** [comment]
> 
> 
> The current firmware does not expose the IKEA bulbs to the API.

Hi! The new firmware version is 1.4.1_167.0158 and i have the same probleme.

**Comment by brendanheyu** [comment]
I have Ikea GU -10 bulbs, I believe I have the same issue...

**Comment by delicon** [comment]
Any news about this?

**Comment by Electronlibre2012** [comment]
Hello,

i have bought 4 new Aqara Bulbs led light and i have this message...

The bulbs works great on the GW, and GW is up to date...no update available...

Any suggestions?

**Comment by Megachip** [comment]
Same here, only using Xiaomi entities. Latest firmware
