### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by vimgp** [Danielhiversen/PyXiaomiGateway#15]
[PyXiaomiGateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'sensor_switch.aq3', 'sid': '158d0001d5807d', 'short_id': 14149, 'data': '{"voltage":3025}'}

**Comment by Danielhiversen** [comment]
Do you have a link with more info about the device?

**Comment by vimgp** [comment]
Bought from TMALL:
https://detail.tmall.com/item.htm?id=556436444442&spm=a1z09.2.0.0.54517d3dmLQ323&_u=i1scbfb64af

**Comment by syssi** [comment]
Home Assistant 0.56.2 supports the new sensor now. Please give it a try and report back!

**Comment by Danielhiversen** [comment]
No, the PyXiaomiGateway library will not be updated before 0.57
