### ISSUE TITLE
Aqara S2 Lock support

### ISSUE THREAD

**Issue by dzungpv** [Danielhiversen/PyXiaomiGateway#153]
I have Aqara S2 Lock model: lumi.lock.acn02 https://www.aliexpress.com/item/Original-xiaomi-mijia-aqara-smart-door-lock-s2-work-with-mi-home-app-For-xiaomi-smart/32875412344.html
How to support it? Any guide how to change the code i could try?
Now hass show this:
```
"The device with sid 158d000xxxxxx isn't supported of the used gateway firmware. Please update the gateway firmware if possible! This is the only way the issue can be solved."
```

**Comment by syssi** [comment]
Did you read this notice: Please update the gateway firmware if possible! This is the only way the issue can be solved.

**Comment by dzungpv** [comment]
@syssi I have update to the latest firmware. I guest the device not support in the code.
