### ISSUE TITLE
Aqara Smart Curtain Motor B1 - unsupported device (ZNCLDJ12LM)

### ISSUE THREAD

**Issue by obtusa** [Danielhiversen/PyXiaomiGateway#156]
I've installed new aqara curtain motor B1
I got this error:

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'curtain.hagl04', 'sid': '4cf8cdf3c73e1cc', 'short_id': 50904, 'data': '{"voltage":3000,"curtain_level":"100"}'}

here is the link to the device
[aliexpress](https://ko.aliexpress.com/item/Xiaomi-aqara-b1-wifi-app/33041179442.html?aff_platform=promotion&cpt=1563314594752&onelink_item_from=33041179442&dp=www.eyelighting.co.uk&onelink_thrd=0.0&onelink_page_from=ITEM_DETAIL&onelink_item_to=33041179442&pvid=68db6f91-d284-40b6-8674-b71672ddd7f3&onelink_duration=0.855628&sk=RBkBY40&aff_trace_key=07a4c28c5f2d4a99afebb8521a04a6c1-1563314594752-09703-RBkBY40&onelink_status=noneresult&scm=1007.22893.125778.0&terminal_id=6c52a2d79fd541b7b6e6e61fa7dcfe44&onelink_page_to=ITEM_DETAIL)

**Comment by ChipSkylark37** [comment]
How could we go about getting this commit into HomeAssistant? I just updated to the latest version of HA (0.97.2) and it's showing this same message:

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'curtain.hagl04', 'sid': 'MAC ADDRESS', 'short_id': 38587, 'data': '{"voltage":3000,"curtain_level":"100"}'}

Would love to get these controllable through HA and subsequently through Google Home.

**Comment by syssi** [comment]
I will update the HA component this week.
