### ISSUE TITLE
The device with sid 158d000396ac06 isn't supported of the used gateway firmware. Please update the gateway firmware if possible! This is the only way the issue can be solved.

### ISSUE THREAD

**Issue by Electronlibre2012** [Danielhiversen/PyXiaomiGateway#158]
**Home Assistant release with the issue (if applicable):**
Home Assistant 0.96.5

**Last working Home Assistant release (if known):**

**PyXiaomiGateway library version (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**
Hass.io supervisor 170
HassOS 2.12

**Traceback (if applicable):**
```

```

**Description of the bug:**
Hello,

Xiaomi Mio gateway V3 firmware 1.41.1_170.0158, no update available
or
Xiaomi Aqara gateway V1(compatible Homekit) firmware 1.6.2_003, no update available

i have bought 4 new Aqara Bulbs led light and i have this message...

The bulbs works great on the GW, and GW is up to date...no update available...

Any suggestions?

The name in Hassio for the led light is like : lightbulb_4204 on a Aqara Gateway V1 and it became 158d0003994204 on the Mio gateway V3 and generate this error in hassio...

So : need a V1 for light bulbs and PIR sensor, and need a V3 for door sensors. But my house as a first floor, so i need both x2...that the only solution i found...so i have 2 GW Aqara V1 and 2 GW Mio V3...LOOOOL

**Comment by syssi** [comment]
A gateway firmware is required which supports the device via the LAN protocol. At the moment the bulbs aren't supported.

**Comment by Electronlibre2012** [comment]
thanks @syssi for your response,

so its a Xiaomi problem?

Perhaps they will never fix it...doesnt care about HA users...

**Comment by syssi** [comment]
Nobody knows. This library implements the LAN protocol. Unexposed devices/features cannot be supported.
