### ISSUE TITLE
Change Light Migateway to unavailable when migate cannot be reached 

### ISSUE THREAD

**Issue by tyjtyj** [Danielhiversen/PyXiaomiGateway#168]
**Home Assistant release with the issue (if applicable):**

108.5
**Last working Home Assistant release (if known):**
Never. Possible feature request

**PyXiaomiGateway library version (if known):**

**Operating environment (Hass.io/Docker/Windows/etc.):**
Venv

**Traceback (if applicable):**
```
ERROR (SyncWorker_12) [xiaomi_gateway] Cannot connect to Gateway
```

**Description of the bug:**

Request to change light.migateway to unavailable when Hass failed to connect to mi gateway
This way to monitor/track mi gateway has disconnected from home assistant. Can be use to trigger alarm or restart router etc.

**Comment by PaulAnnekov** [comment]
This should go to HA repo. Please, close this issue.

**Comment by tyjtyj** [comment]
Mind point out where should I open this case ?

**Comment by PaulAnnekov** [comment]
https://github.com/home-assistant/core/issues

**Comment by tyjtyj** [comment]
Thanks
