### ISSUE TITLE
Config Flow

### ISSUE THREAD

**Issue by starkillerOG** [Danielhiversen/PyXiaomiGateway#169]
@Danielhiversen are there any plans to update the HomeAssistant Xiaomi Aqara component to use Config Flow?
If nobody is currently working on Config Flow or planning on implementing Config Flow, I would be willing to do it, but I first wanted to know if someone else was already working on it.

Do not want to do double work...

On a sidenode, the discovery of the xiaomi gateway is done using mdns I think, but why is the HomeAssistant zeroconf not picking up the xiaomi gateway?
(of course there is no code to handel a discovered gateway, but if you enable debug on the zeroconf component I think it schould give you all raw responses on the mdns scan before an attempt is made to identify the devices, the xiaomi gateway does not show up in my debug log)

Does the Xiaomi discovery protecoll use a diffrent multicast group or port or something?

**Comment by Danielhiversen** [comment]
It would be great if you would do that.

**Comment by starkillerOG** [comment]
I will start working on the Config Flow soon, If I run into problems I hope you might be willing to provide some advise

**Comment by starkillerOG** [comment]
For those who are instrested, my current progress on the config flow is in this fork: https://github.com/starkillerOG/home-assistant/tree/patch-26

However it is not ready for testing!
Still need to do quite some work, but the basis is there.

**Comment by starkillerOG** [comment]
I now have the Config flow working in my dev enviroment. just some code cleanup and writing tests to do.
The HomeAssistant PR is here: https://github.com/home-assistant/core/pull/35595
