### ISSUE TITLE
Support for Aqara wall smart switch D1 (2020 model)

### ISSUE THREAD

**Issue by chewbh** [Danielhiversen/PyXiaomiGateway#173]
**Home Assistant release with the issue (if applicable):**
0.112.3

**Last working Home Assistant release (if known):**
not applicable

**PyXiaomiGateway library version (if known):**
not known

**Operating environment (Hass.io/Docker/Windows/etc.):**
Docker

**Traceback (if applicable):**
Logger: xiaomi_gateway
Source: util/thread.py:20
First occurred: 22:58:38 (1 occurrences)
Last logged: 22:58:38

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b1lacn02', 'sid': '158d00048663f8', 'short_id': 43756, 'data': '{"voltage":3300,"channel_0":"on"}'}

**Description of the bug:**
The newer version of Xiaomi / Aqara wall switch (non-neutral version) is not supported. Any plan to support this?

**Comment by syssi** [comment]
Fixed.
