### ISSUE TITLE
Push the release to pypi please

### ISSUE THREAD

**Issue by nickrout** [Danielhiversen/PyXiaomiGateway#176]
Version 13.0 needs to be placed on pypi please? Seems to be still at 12.4 which in turn seems to be a problem for home assistant 0.112.x.

Sorry if this is under way already or if I missed something.

**Comment by stevoh6** [comment]
I think he did it, but Travis tests failed. See : https://travis-ci.org/github/Danielhiversen/PyXiaomiGateway

**Comment by nickrout** [comment]
@Danielhiversen

**Comment by stevoh6** [comment]
FYI @Danielhiversen Travis still not pass :/

**Comment by Danielhiversen** [comment]
@nickrout @stevoh6 You are welcome to fix the failing tests

**Comment by nickrout** [comment]
Sorry I wish I had the skills. And I'm on holiday, just using my phone. Might try and upskill at end of holiday ;)

**Comment by syssi** [comment]
Fixed by 0.13.1.

**Comment by syssi** [comment]
@Danielhiversen I've fixed the build issue but dpl cannot upload the new release to pypi at the moment: https://travis-ci.org/github/Danielhiversen/PyXiaomiGateway/builds/711902687#L457

Could you help here?

**Comment by Danielhiversen** [comment]
Fixed

**Comment by stevoh6** [comment]
> @nickrout @stevoh6 You are welcome to fix the failing tests

I wish to has skills in Python or with Travis. Unfortunately I don't. This wasn't written with heist. Anyway, thank you very much 👍
