### ISSUE TITLE
Pls add support for new type wall switch of Xiaomi

### ISSUE THREAD

**Issue by lxh0508** [Danielhiversen/PyXiaomiGateway#178]
Homeassistant version: 0.112.4
OS: Docker base on Synology DSM 6.2.3

Thank you very much.

Logger: xiaomi_gateway
Source: util/thread.py:20
First occurred: 下午10:32:12 (24 occurrences)
Last logged: 下午10:32:56

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b1nacn02', 'sid': '158d00047da7df', 'short_id': 3968, 'data': '{"voltage":3600,"channel_0":"off"}'}
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b1nacn02', 'sid': '158d00045edb96', 'short_id': 37843, 'data': '{"voltage":3600,"channel_0":"off"}'}
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b1nacn02', 'sid': '158d00045eda82', 'short_id': 50951, 'data': '{"voltage":3600,"channel_0":"off"}'}
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b2nacn02', 'sid': '158d0004834474', 'short_id': 47693, 'data': '{"voltage":3600,"channel_0":"off","channel_1":"off"}'}
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b2nacn02', 'sid': '158d000483457d', 'short_id': 49195, 'data': '{"voltage":3600,"channel_0":"off","channel_1":"off"}'}

**Comment by lxh0508** [comment]
Homeassistant version: 0.112.4
OS: Docker base on Synology DSM 6.2.3

Thank you very much.

Logger: xiaomi_gateway
Source: util/thread.py:20
First occurred: 下午10:32:12 (24 occurrences)
Last logged: 下午10:32:56

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b1nacn02', 'sid': '158d00047da7df', 'short_id': 3968, 'data': '{"voltage":3600,"channel_0":"off"}'}
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b1nacn02', 'sid': '158d00045edb96', 'short_id': 37843, 'data': '{"voltage":3600,"channel_0":"off"}'}
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b1nacn02', 'sid': '158d00045eda82', 'short_id': 50951, 'data': '{"voltage":3600,"channel_0":"off"}'}
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b2nacn02', 'sid': '158d0004834474', 'short_id': 47693, 'data': '{"voltage":3600,"channel_0":"off","channel_1":"off"}'}
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'switch_b2nacn02', 'sid': '158d000483457d', 'short_id': 49195, 'data': '{"voltage":3600,"channel_0":"off","channel_1":"off"}'}

**Comment by syssi** [comment]
Fixed.
