### ISSUE TITLE
Unsuported device (Aqara wall switch D1 single rocker with neutral)

### ISSUE THREAD

**Issue by crowley285** [Danielhiversen/PyXiaomiGateway#182]
My Hass log is telling me this switch is not supported yet (Aqara wall switch D1 single rocker with neutral)
{'cmd': 'read_ack', 'model': 'switch_b1nacn02', 'sid': '158d000578c4b7', 'short_id': 1002, 'data': '{"voltage":3600,"channel_0":"on"}'}

I am currentrly running Home Assistant v0.113.2

**Comment by tyjtyj** [comment]
@syssi luck with this ?

**Comment by crowley285** [comment]
fixed in HomeAssistant version 0.114.0
