### ISSUE TITLE
i can't use Aqara D1 Wireless Remote Switch (Single Rocker) (WXKG06LM) (lumi.remote.b186acn02) in homeassistant 0.114.3

### ISSUE THREAD

**Issue by BG1KAP** [Danielhiversen/PyXiaomiGateway#185]
i upgrade my homeassistant to 0.114.3 ,  but Aqara D1 Wireless Remote Switch (Single Rocker) (WXKG06LM) can not used , why?
i using raspberrypi + docker + homeassistant

,2020-08-21 00:27:55 ERROR (SyncWorker_10) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b186acn02', 'sid': '158d00041c6500', 'short_id': 15356, 'data': '{"voltage":3095}'}
,2020-08-21 00:27:55 ERROR (SyncWorker_10) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b186acn02', 'sid': '158d00042c1cf5', 'short_id': 4982, 'data': '{"voltage":3115}'}
,2020-08-21 00:27:55 ERROR (SyncWorker_10) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b186acn02', 'sid': '158d00045b2906', 'short_id': 17902, 'data': '{"voltage":3105}'}

**Comment by sylv1697** [comment]
Hello, i have the same issue.
https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b186acn02', 'sid': '158d0004651b36', 'short_id': 61293, 'data': '{"voltage":3055}'}
As someone as a solution ?

**Comment by settler-als** [comment]
Logger: xiaomi_gateway
Source: /usr/local/lib/python3.8/site-packages/xiaomi_gateway/__init__.py:309
First occurred: 0:21:00 (1 occurrences)
Last logged: 0:21:00

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b186acn02', 'sid': '158d00042c0239', 'short_id': 12282, 'data': '{"voltage":3025}'}

**Comment by fabricepipart** [comment]
I think this model has just been forgotten when those two commits were made:
https://github.com/Danielhiversen/PyXiaomiGateway/commit/88699a2ea3f06f258ed644f7acb9836df5e24249
and
https://github.com/Danielhiversen/PyXiaomiGateway/commit/f0742e12747d44ba353ba740bf796fadcbbae420

This should just be a matter of referencing the button model here:
https://github.com/Danielhiversen/PyXiaomiGateway/blob/master/xiaomi_gateway/__init__.py#L262

I'll try to do a fix ASAP. On the other side, it seems to be correctly referenced on HA side:
https://github.com/home-assistant/core/commit/3fc5f9deb82e855d69aa7001df96c5820a62554c

**Comment by fabricepipart** [comment]
@syssi It seems that there is no automatic releasing for this repository. Any idea when a new version can be released so that we reference it in Home Assistant to have the new button type supported?

**Comment by syssi** [comment]
I've prepared a new release. Do you like to prepare a PR for Home Assistant (make sure the model is handled properly + version bump)?

**Comment by fabricepipart** [comment]
Thanks for the new release 👍 

Indeed I can give some help and do the PR on HA side. I may just have a few questions but I plan to do something that looks like this:
https://github.com/home-assistant/core/commit/3fc5f9deb82e855d69aa7001df96c5820a62554c

**Comment by syssi** [comment]
I've reviewed the old PR. In this case just a version bump to 0.13.3 is required.
