### ISSUE TITLE
Unsupported device found

### ISSUE THREAD

**Issue by ilzc** [Danielhiversen/PyXiaomiGateway#20]
Hi, 
 It logged out "Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'sensor_switch.aq3', 'sid': '158d0001d47acd', 'short_id': 57945, 'data': '{"voltage":3015}'}".
  with Home-Assistant 0.56.2. And I'm not sure which version of PyXiaoiGateway is included.

**Comment by Danielhiversen** [comment]
This should be solved in Home-Assistant 0.57
