### ISSUE TITLE
Looking forward to support aqara fingerprint door lock

### ISSUE THREAD

**Issue by cnberg** [Danielhiversen/PyXiaomiGateway#22]
After setup  aqara fingerprint door lock and restart hass, I got the following msg at the console:

> {'sid': '158d0001e17xxx', 'data': '{"voltage":3398}', 'model': '', 'cmd': 'read_ack', 'short_id': 183}

There is no model info.

**Comment by syssi** [comment]
In this case the current firmware of your gateway doesn't support the new device yet. Please install the upcoming firmware and report the device name if available.

**Comment by cnberg** [comment]
Thanks for your reply.

I have upgraded to the newest version(1.4.1_150.0143) before, and I can see
the event log by the door in MiJia app, but still get no model info.

So I have to waiting for a newer version?



--------------
Yours sincerely
berg
http://cnberg.com
@cnberg

**Comment by syssi** [comment]
Yes!
