### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by mylinc** [Danielhiversen/PyXiaomiGateway#23]
2017-11-23 00:50:10 ERROR (SyncWorker_3) [PyXiaomiGateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': '', 'sid': '158d0001f24793', 'short_id': 14223, 'data': '{"voltage":3600}'}

The device is xiaomi switch(Aqara Wall Switch LN (Double) ,The newest version),I see information in gateway is  (Model: lumi.ctrl_ln2.aq1), I found Model is change，last version is (Model: lumi.ctrl_ln2.v1),help me.pls...

**Comment by syssi** [comment]
As long as the gateway reports an empty model name the device isn't supported of the current gateway firmware. Please wait for the next firmware release of xiaomi.

**Comment by syssi** [comment]
I will add the ctrl_ln2.aq1 to be prepared.

**Comment by syssi** [comment]
Hmm... It's uncertain the new device model will be "ctrl_ln2.aq1". As far as the new model name is known I will provide some changes.

**Comment by mylinc** [comment]
tks,have plans yet?

**Comment by syssi** [comment]
It's up to xiaomi releasing a new gateway firmware.

**Comment by mylinc** [comment]
I update gateway firmware to 1.4.1_150.0143
but still error

2017-12-01 22:04:25 ERROR (SyncWorker_3) [PyXiaomiGateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': '', 'sid': '158d0001f24793', 'short_id': 14223, 'data': '{"voltage":3600}'}

**Comment by zxjack** [comment]
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': '', 'sid': '158d0001f27b69', 'short_id': 45074, 'data': '{"voltage":3600}'}

**Comment by cxlwill** [comment]
I guess all Aqara Wall Switch has updated to new version, which means that relevant model names changed to `ctrl_neutral1.aq1/ctrl_neutral2.aq1` & `ctrl_ln1.aq1/ctrl_ln2.aq1`.

**Comment by syssi** [comment]
As long as the gateway response with an empty model name

> data: {'cmd': 'read_ack', 'model': '', ...}

a new gateway firmware is required. Please be patient!

**Comment by cxlwill** [comment]
BTW, there is a new version (v2.0.0) of Aqara LAN protocol ready to be out. Second version of Aqara Air Condition Companion has already used it, which is under beta test. Maybe new switch is using it. I assume we would face with some changes next year (month). But you are right, still we need updated gateway's firmware to tell the differences. Xiaomi has pushed update 1.4.1_151.0143 earlier this week. I wonder if there are any new feedbacks.

**Comment by cxlwill** [comment]
@zxjack @mylinc Have you updated your gateway to 1.4.1_151.0143？Any positive feedbacks? (For connivence, I translate it into Chinese: 你们更新网关固件到 1.4.1_151.0143 了吗？有新的反馈吗？）

**Comment by acui** [comment]
@cxlwill I have an 1.4.1_151.0143 gateway and a lumi.ctrl_ln1.aq1 switch. The gateway reports an empty model name too. And I also got a lumi.ctrl_86plug.aq1 wall plug. It has the same problem.

**Comment by zxjack** [comment]
@cxlwill I had updated my gateway to 1.4.1_151.0143.The problem is same.
2017-12-21 15:22:07 ERROR (SyncWorker_2) [PyXiaomiGateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': '', 'sid': '158d0001f27b69', 'short_id': 23272, 'data': '{"voltage":3600}'}

**Comment by pataha** [comment]
same issue here, gateway firmware `1.4.1_151.0143`, device: `lumi.ctrl_ln2.aq1`

**Comment by shenxn** [comment]
Any updates? It seems that the new version of the LAN protocol is already released: http://docs.opencloud.aqara.cn/development/gateway-LAN-communication/

**Comment by syssi** [comment]
Do I miss something? The release date of (the newest) version 2.0.1 is pretty old. There is no new firmware with updated network protocol right now.

**Comment by shenxn** [comment]
There is a new discovery command, so maybe the protocol is already in the firmware. I don't have any devices on hand right now so I'm not sure.

**Comment by syssi** [comment]
No. The discovery command is just a remote command instead of pushing the button of the gateway three times (already tested).

**Comment by ayufan** [comment]
Interestingly. These new devices can be connected when using https://github.com/aholstenson/miio/. You only need to add it to additional types: https://github.com/aholstenson/miio/blob/master/lib/devices/gateway/subdevices.js#L3.

**Comment by syssi** [comment]
As long as the gateway reports an empty model name the device cannot be used or added to the subdevices.js.

**Comment by ayufan** [comment]
@syssi There are two different APIs available which can be used, the second one offers a way to detect and support new devices.

I'm talking about this API: https://github.com/OpenMiHome/mihome-binary-protocol

**Comment by gsotiriou** [comment]
Hello , are there any updates coming? I too have an unsupported GW and it gives me grief as it sometimes makes the whole HA hang

**Comment by syssi** [comment]
Is your gateway unsupported or a specific subdevice? Please contact the manufacturer.

**Comment by gsotiriou** [comment]
@syssi my GW is not supported and produces the following data on HA:
{'data': '{"voltage":3600,"channel_0":"off"}', 'cmd': 'read_ack', 'model': '', 'short_id': 54865, 'sid': '158d0001f2ada8'}

**Comment by syssi** [comment]
@gsotiriou Are you sure this is a gateway? I think the error message is of an unsupported wall switch.

**Comment by gsotiriou** [comment]
@syssi you are correct indeed. Thanks for that! Problem now is I cannot find which device this is , I have about seven wall switches wired into the wall and another wireless one. But that's beyond the scope of this project so just thank you!

**Comment by kukki** [comment]
I bought both latest version of Aqara smart wall switch and Aqara smart wall plug. And I have an old Aqara smart wall switch. I have same issue as above.

My gateway info is 
```
Sub-device
{ Model: lumi.ctrl_ln2.v1,did: lumi.158d00019cfxxx,name: 排气扇/灯 } -- old version wall swtich
{ Model: lumi.ctrl_ln2.aq1,did: lumi.158d00022b7xxx,name: 台灯/日光灯 } -- new version wall switch
{ Model: lumi.ctrl_86plug.aq1,did: lumi.158d0002014xxx,name: 墙壁插座(zigbee版) } -- wall plug
Gatway:
version: 2.49.3, version code: 169
Firmware version: 1.4.1_151.0143 (currently the latest one)
```
`lumi.ctrl_ln2.v1` works perfectly while `ctrl_86plug.aq1` and `ctrl_ln2.aq1` are not identified. In Mi Home app, there is no status available below the new wall switch icon.
![Mi Home App](https://image.ibb.co/mq8xkn/aqara2.png)

**Comment by qk4l** [comment]
@Danielhiversen  " Please update the gateway firmware if  possible! This is the only way the issue can be solved."

Do I understand correctly that no one is interesting in investigation of this problem?
 
@ayufan suggested [here](https://github.com/Danielhiversen/PyXiaomiGateway/issues/23#issuecomment-359250700)  that probably Xiaomi is switching to the new protocol.  In this case `ctrl_ln2.aq1` will never stats work with this library nor any new devices.

**Comment by Danielhiversen** [comment]
> Do I understand correctly that no one is interesting in investigation of this problem?

No, we are interested in finding a solution to the problem.
But with the current protocol we are using, we need the model to be specified. Normally Xiaomi will publish a new firmware that support new devices and then packet will include a model name.
Before the  40cc5af commit we got a lot of issues where the model name is empty, and that is not of any use.

**Comment by syssi** [comment]
I have added the prospective model names of a upcoming release: https://github.com/Danielhiversen/PyXiaomiGateway/pull/53

This doesn't mean the devices are supported now. As long as the gateway reports an empty model name the devices cannot be used. Devices with empty model names doesn't respond to requests! The device support of the gateway firmware is inevitable here.

I will check if unsupported devices can be accessed by github.com/rytilahti/python-miio/ (the alternative protocol for polling xiaomi mi devices) mentioned by @ayufan and @qk4l.

**Comment by pataha** [comment]
the new firmware has been released
from logs:
`{'cmd': 'read_ack', 'model': 'ctrl_ln2.aq1', 'sid': 'xxxxxxxxxxxx', 'short_id': 43069, 'data': '{"voltage":3600}'}`

**Comment by Danielhiversen** [comment]
It is already added to HA, and will be part of the next release.

**Comment by pataha** [comment]
It sill report as ‘unsupported device found’ with HA 0.64.1

**Comment by gsotiriou** [comment]
@pataha maybe you don't have the newest firmware on your gateway yet?

**Comment by syssi** [comment]
"will be part of the next release" == 0.65

**Comment by kukki** [comment]
After I upgrade hass to 0.54.1, the new device model name can be extracted. They look like:
```
{'sid': '158d000201xxxx', 'short_id': 20500, 'data': '{"voltage":3600,"status":"off","inuse":"0"}', 'cmd': 'read_ack', 'model': 'ctrl_86plug.aq1'}
{'sid': '158d00022bxxxx', 'short_id': 42600, 'data': '{"voltage":3600}', 'cmd': 'read_ack', 'model': 'ctrl_ln2.aq1'}
```
I copy `xiaomi_gateway/__init__.py` from 0.8.2 tag (file commit: f47e4de15b229643ec10e82ad4a23d7049df6c14) to replace `~/.homeassistant/deps/lib/python3.5/site-packages/xiaomi_gateway/__init__.py`, and update the line 228 from
```
'86plug', '86plug.aq1'],
```
to
```
'86plug', '86plug.aq1', 'ctrl_86plug.aq1'],
```
Now there is no more `unsupported device found` error in the log.
But the new model devices are not shown in the hass entities list or in the log.

**Comment by syssi** [comment]
Homeassistant also needs to be updates. I will fix the incorrect model name today!

**Comment by syssi** [comment]
@cxlwill prepared a PR already: #56 

The corresponding line in home assistant is fine. The new devices will be part of the next HA release (0.65):

https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/switch/xiaomi_aqara.py#L55

**Comment by kukki** [comment]
Can't wait for the next release of home assistant.
Manually updating both files makes new devices work perfectly.
* `~/.homeassistant/deps/lib/python3.5/site-packages/xiaomi_gateway/__init__.py` 
* `/usr/local/lib/python3.5/dist-packages/homeassistant/components/switch/xiaomi_aqara.py`

Thank you @syssi

**Comment by pataha** [comment]
me too, cant wait to see.
Manually updating above 2 files make it works

Finally, `ctrl_ln2.aq1` shows up and works properly
Thanks all
