### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by micy3us** [Danielhiversen/PyXiaomiGateway#24]
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'data': '{"voltage":3025}', 'cmd': 'read_ack', 'sid': '158d000171f3e3', 'model': '', 'short_id': 13946}

Log error from homeassistant.
Device is temp and humidity sensor "square version": https://xiaomi-mi.com/sockets-and-sensors/aqara-temperature-and-humidity-sensor/

**Comment by syssi** [comment]
Please check the firmware version of your gateway. Which version do you use?

**Comment by micy3us** [comment]
Gateway firmware version 1.4.1_147.0143. There is a later version 1.4.1_150.0143 available, should I upgrade?

The old temp and humidity sensors are working fine.  https://xiaomi-mi.com/sockets-and-sensors/xiaomi-mi-temperature-humidity-sensor/

**Comment by micy3us** [comment]
Upgraded to the latest version. Working fine now!
