### ISSUE TITLE
"Cannot connect to Gateway" should be followed by "Reconnected to Gateway"

### ISSUE THREAD

**Issue by PaulAnnekov** [Danielhiversen/PyXiaomiGateway#25]
I have setup a log watcher which checks for errors in logs and some trigger words and sends them to an email. Sometimes I see "Cannot connect to Gateway" error in HA logs which means we didn't receive response from socket in 10 seconds.
I want to ask you to add "Reconnected to Gateway" log message which will be printed once we see connection to Gateway is OK again, so I will add these words to log watcher and see two emails:
> 2017-11-27 12:55:00 Cannot connect to Gateway

> 2017-11-27 12:55:46 Reconnected to Gateway

Now I see only 1st and need to check manually if connection is OK again.

**Comment by Danielhiversen** [comment]
It will not reconnect before another message is send.
So do not plan implement such feature now. But you are welcome to open a pr.
