### ISSUE TITLE
 Unsupported device found!

### ISSUE THREAD

**Issue by mystryl** [Danielhiversen/PyXiaomiGateway#27]
[PyXiaomiGateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': '', 'sid': '158d0001f2ac76', 'short_id': 15011, 'data': '{"voltage":3600,"channel_0":"on"}'}

similar error here, but my device is lumi.ctrl_ln1.aq1.

i do change the __init__.py adding ctrl_ln1.aq1 and ctrl_ln2.aq1
and change the /components/xiaomi_aqara.py adding these two.
nothing happen.

maybe because the 'model‘  is blank? how to fix that? plz!

**Comment by syssi** [comment]
Please compare:

https://github.com/Danielhiversen/PyXiaomiGateway/issues/24
https://github.com/Danielhiversen/PyXiaomiGateway/issues/23

Please update your gateway firmware via the Xiaomi MiHome app.

**Comment by mystryl** [comment]
my firmware is latest 1.4.1_150.0143, still report blank model type...
maybe i'll just wait..

**Comment by syssi** [comment]
In this case you have a new and unsupported hardware revision of the device and you have to wait for a new gateway firmware.
