### ISSUE TITLE
Millet zero fire two-button version of the switch can not access Home Assistant

### ISSUE THREAD

**Issue by xujianliang** [Danielhiversen/PyXiaomiGateway#28]
data: {'cmd': 'read_ack', 'model': '', 'sid': '158d0001ef5822', 'short_id': 49373, 'data': '{"voltage":3600}'}

**Comment by Danielhiversen** [comment]
As long as the gateway reports an empty model name the device isn't supported of the current gateway firmware. Please wait for the next firmware release of xiaomi.
