### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by jasimancas** [Danielhiversen/PyXiaomiGateway#29]
{'cmd': 'read_ack', 'model': '', 'sid': '158d0001f4e65f', 'short_id': 9672, 'data': '{"voltage":3600}'}

**Comment by syssi** [comment]
Please compare https://github.com/Danielhiversen/PyXiaomiGateway/issues/23

**Comment by jasimancas** [comment]
Not, in this case is "lumi.ctrl_86plug.aq1" is a Aqara Wall Plug

**Comment by syssi** [comment]
Which gateway firmware do you use?

**Comment by jasimancas** [comment]
1.4.1_151.0143

**Comment by meanstech** [comment]
I received an error message too:
{'cmd': 'read_ack', 'model': '', 'data': '{"voltage":3600}', 'short_id': 23954, 'sid': '158d0001f4e229'}

**Comment by jasimancas** [comment]
@meanstech what device is?

**Comment by meanstech** [comment]
@jasimancas Aqara Smart Wall Plug : QBCZ11LM

thanks!

**Comment by jasimancas** [comment]
Same here lumi.ctrl_86plug.aq1
