### ISSUE TITLE
Aqara Wireless Switch (Double) have some trouble

### ISSUE THREAD

**Issue by w729** [Danielhiversen/PyXiaomiGateway#33]
when i press the wireless switch(long click press,single press or double press),the state in hass still keep "off". Why?

Thank you！

hass ver：0.60.0
xiaomi gateway ver：1.4.1_151.0143
Aqara Wireless Switch (Double)：Model: lumi.sensor_86sw2.v1,did: lumi.158d0001639cf9

**Comment by Danielhiversen** [comment]
For long press the state should change.
Enable debug logging for xiaomi and check the log.

But this not an issue for the library, but for HA.

**Comment by syssi** [comment]
In the past the available events of the zigbee entity 86sw2 was: single & both

Please compare https://home-assistant.io/components/binary_sensor.xiaomi_aqara/. 

Are you sure your device supports additional click events now?
