### ISSUE TITLE
Unknown format code 'x' for object of type 'str'

### ISSUE THREAD

**Issue by mickeprag** [Danielhiversen/PyXiaomiGateway#34]
I get this error in [XiaomiGateway._get_key line 326](https://github.com/Danielhiversen/PyXiaomiGateway/blob/master/PyXiaomiGateway/__init__.py#L326)

Changing this to this works (adding ord):
`return ''.join('{:02x}'.format(ord(x)) for x in ciphertext)`

1) Is this a bug or why does it fail for me?
2) Is the fix correct?
3) Should I create a pull request?

**Comment by syssi** [comment]
ciphertext shouldn't be of type "str". This example works fine for me:

```python
init_vector = bytes(bytearray.fromhex('17996d093d28ddb3ba695a2e6f58562e'))
encryptor = Cipher(algorithms.AES(str('00000000000000000000000000000000').encode()), modes.CBC(init_vector),backend=default_backend()).encryptor()
ciphertext = encryptor.update(str('00000000000000000000000000000000').encode()) + encryptor.finalize()
''.join('{:02x}'.format(x) for x in ciphertext)
```

**Comment by mickeprag** [comment]
Works fine in python 3.4.5
Throws the exception in python 2.7.14

ciphertext is `bytes` in python 3 but `str` in python 2

**Comment by mickeprag** [comment]
I suggest using six.byte2int() for compatibility with both python 2 and 3. Does this sound like a reasonable solution?

**Comment by Danielhiversen** [comment]
Python 2 is not supported

**Comment by mickeprag** [comment]
Not officially supporting python 2 is ok for me. But apart from this fix everything else is working.
Would you consider adding this patch to make the library work on Python 2 anyway?
I can create a pull request...

**Comment by syssi** [comment]
Please provide a pull request for your ord(bs[0]) solution. I would like to avoid additional dependencies.
