### ISSUE TITLE
Rewrite the way of working with UDP traffic in XiaomiGateway._send_cmd()

### ISSUE THREAD

**Issue by PaulAnnekov** [Danielhiversen/PyXiaomiGateway#45]
The whole way of dealing with UDP traffic is wrong there. Compared to TCP, UDP guarantees almost nothing.
https://github.com/Danielhiversen/PyXiaomiGateway/blob/master/xiaomi_gateway/__init__.py#L268
The code assumes it will get a response to the request above, but it's too naive. UDP doesn't guarantee order and delivery. Multiple UDP dispatches at the same time can make a lot of bad things, like each `recvfrom()` will get the result of the neighbour. Here is an example of this bug in HA:
```
20:00:53 DEBUG (SyncWorker_12) [xiaomi_gateway] >> b'{ "cmd":"read","sid":"1"}'
20:00:53 DEBUG (SyncWorker_2) [xiaomi_gateway] >> b'{"cmd": "write", "sid": "2", "data": {"rgb": 0, "key": "xxx"}}'
20:00:53 DEBUG (SyncWorker_2) [xiaomi_gateway] << {'cmd': 'read_ack', 'model': 'magnet', 'sid': '1', 'short_id': 43528, 'data': '{"voltage":3035,"status":"open"}'}
20:00:53 ERROR (SyncWorker_2) [xiaomi_gateway] Non matching response. Expecting write_ack, but got read_ack. {'cmd': 'read_ack', 'model': 'magnet', 'sid': '1', 'short_id': 43528, 'data': '{"voltage":3035,"status":"open"}'}
20:00:53 ERROR (SyncWorker_2) [xiaomi_gateway] No data in response from hub None
20:00:53 DEBUG (SyncWorker_12) [xiaomi_gateway] << {'cmd': 'write_ack', 'model': 'gateway', 'sid': '2', 'short_id': 0, 'data': '{"rgb":0,"illumination":312,"proto_version":"1.0.9"}'}
20:00:53 ERROR (SyncWorker_12) [xiaomi_gateway] Non matching response. Expecting read_ack, but got write_ack. {'cmd': 'write_ack', 'model': 'gateway', 'sid': '2', 'short_id': 0, 'data': '{"rgb":0,"illumination":312,"proto_version":"1.0.9"}'}
20:00:53 ERROR (SyncWorker_12) [xiaomi_gateway] No data in response from hub None
```

Devices didn't get right responses, their states were not updated. In case of 2 simultaneous reads, devices can get each others states. As you understood - infinite space for bugs :).

It's OK to have send + immediate receive when you're 100% sure there will be no simultaneous dispatches. But it's not the case of `write_to_hub()` and `get_from_hub()` which can be executed asynchronously without waiting of the previous function to return the result.

What do I propose?

1. Make a single `while True: recvfrom()` per `XiaomiGateway` at least after initialization. It will check for an error/invalid key or call `push_data()` on success which will update the device state.
2. Don't call `recvfrom()` in `_send_cmd()` at least after initialization.
3. Remove checking of `write_to_hub()` result in HA (e.g. https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/light/xiaomi_aqara.py#L98). Hub will respond and single listener will call `push_data`.
4. Add some tracker that will have a list of responses we are waiting. If we didn't get a response for any request in 10 seconds time frame - log an error. If we got a response, but was not waiting for it - log an error. You can use `sid`+`cmd` to identify the response (it's the best we can as there is no way to supply/receive request ids).

Related issue: https://community.home-assistant.io/t/xiaomi-gateway-errors-but-seems-to-be-working-fine/38633

**Comment by Danielhiversen** [comment]
I agree.
I only have one gw and then it works fine.
So the multi gw solution is an old implementation, that I have never tested.

A pull request is welcome :)

**Comment by PaulAnnekov** [comment]
You will have this issue even with a single gateway. You just need several XiaomiDevices (like XiaomiMotionSensor) to make a request to gateway at the same time. And there will be a big chance of failure and broken state.

**Comment by Danielhiversen** [comment]
You are right

**Comment by heff27** [comment]
I have noticed since upgrading to 0.62.1 i am getting a lot of Unavailable status on the window and door sensors, a restart of HA, fixes this for a white while.

**Comment by PaulAnnekov** [comment]
@heff27 it can indicate that your local network is not very stable and loses packets sent by gateway.

Can you enable debug logging and provide us `xiaomi_gateway`/`homeassistant.components.xiaomi_aqara` logs for the last 2 days:
```
logger:
  logs:
    xiaomi_gateway: debug
    homeassistant.components.xiaomi_aqara: debug
```
?

Device becomes unavailable when it doesn't send at least one packet of data in 2.5 hours. So if you don't see any `report`/`read_ack`/`write_ack`/`heartbeat` from your device in 2.5 hours time frame - you get `unavailable` state. Restarting HA just resets this 2.5 hours timer and countdown begins from start :).

**Comment by PaulAnnekov** [comment]
@heff27 do it like this:
```
logger:
  default: error
  logs:
    xiaomi_gateway: debug
    homeassistant.components.xiaomi_aqara: debug
```
This will log only `error` logs and all xiaomi-related logs. After 2 days provide us a log file. Read here how you can get all logs as a file: https://home-assistant.io/components/logger/#service-set_level.

**Comment by heff27** [comment]
HI please attached the log file as requested, if you need anymore information please let me know 

Thanks 
[home-assistant.log.zip](https://github.com/Danielhiversen/PyXiaomiGateway/files/1708815/home-assistant.log.zip)

**Comment by PaulAnnekov** [comment]
I have greped your log and didn't find any problems during this period. I have checked 4 sids: `158d0001a98550`, `158d0001a98401`, `158d0001d86d4a` and `158d0001d5c426` with the command like this: `egrep "homeassistant.components.xiaomi_aqara.*158d0001d5c426" home-assistant.log`.
I see that you have at least 1 `PUSH` per hour which means you shouldn't have any unavailabilities. Can you specify at which time did you have unavailability status and for which sids?

**Comment by heff27** [comment]
158d0001a4c991 7 158d00019e0551 were the sensors that we going into unavailable state but these have seem to have stopped ever since i rebooted after adding the Debug Config.... Sorry probably not what you was looking for..

I am still getting loads of these errors that you can see in the log 

No data in response from hub None
23:20 components/binary_sensor/xiaomi_aqara.py (ERROR)
No data in response from hub None
23:20 components/light/xiaomi_aqara.py (ERROR)
Non matching response. Expecting read_ack, but got write_ack
23:20 components/binary_sensor/xiaomi_aqara.py (ERROR)
Non matching response. Expecting write_ack, but got read_ack
23:20 components/light/xiaomi_aqara.py (ERROR)

**Comment by PaulAnnekov** [comment]
If you want me to debug unavailability state, you need to provide logs, sids and time when state switch happenned.

> I am still getting loads of these errors that you can see in the log
Yes, that's what is explained in this issue and will be fixed. But it's not always connected with unavailability.

**Comment by heff27** [comment]
I had an unavailability status late Friday night around 11pm i looked in the log and nothing. I looked on the MI apps and the sensor was showing unavailable also.... but yesterday I was back available again with no interaction....

**Comment by monster1025** [comment]
I have same issue with HA component, packet miss/wrong packets(write command other than recieved data)/socket timeouts. It happens often when client (raspberry pi 3 in my case) is connected over wifi network and less often when client is connected over ethernet.

**Comment by Renato-Menna** [comment]
> So the multi gw solution is an old implementation, that I have never tested.

I can confirm that with 3 gateways each time I restart HA at least one of the gateways is not found.

Have you or PaulAnnekov started any work on the UDP refactoring? I would like to help.

**Comment by UmerFraz** [comment]
i get the non-matching error too. my gateway seems to have been discovered and responds to the ringtone commands. but no attached devices are discovered.

**Comment by Martinvdm** [comment]
Having the same issues. errors like:
```
[xiaomi_gateway] Cannot connect to Gateway
[xiaomi_gateway] No data in response from hub None
```
Having a about 6 door/window sensors.

**Comment by Barrysv** [comment]
I have been getting the "cannot content to Gateway" and "No data in response from hub None" since setting up the Xiaomi gear back in Dec last year.  The Xiaomi gear works really well 99% of the time but have witnesses automations not turn switches on at the scheduled time only to check the HA logs to see that at the same time the above connection errors had occurred.

Hoping I could solve this by brute force,  I changed my network setup so my Aqara gateway is on its own access point in close range and on its own vlan with the home assistant. Network traffic is low.  
However since this network topology change I still get the connect connect and no data in response messages in the logs and have seen switches not turn on when they were supposed to.

I wonder if the ultimate solution is to implement point 4 mentioned by Paul?  Suggest that HA checks for the acknowledgment within a timeout period and if not it resends the request?

**Comment by PaulAnnekov** [comment]
I'm gonna fix this bug this week.

**Comment by Barrysv** [comment]
Hi Paul/Daniel is this ready to test? I can help

**Comment by PaulAnnekov** [comment]
@Barrysv yes. It's merged now.

**Comment by Barrysv** [comment]
@PaulAnnekov been testing it today - no connection errors in the log and the Xiaomi devices working as expected.  Great job

**Comment by PaulAnnekov** [comment]
I think this bug was fixed. Closing the issue.

**Comment by cosinguyen** [comment]
Hi,
Sorry my code skill very bad. So what i need to do in this case. I using newest version of HassIO with docker.

Thanks.
