### ISSUE TITLE
problem with new aqara wall plugin

### ISSUE THREAD

**Issue by ipmerlin** [Danielhiversen/PyXiaomiGateway#48]
ERROR (SyncWorker_10) [xiaomi_gateway] Unsupported device found!
{'cmd': 'read_ack', 'model': '', 'sid': '158d00020100d5', 'short_id': 4235, 'data': '{"voltage":3600}'}
QBCZ11LM made in 2017.11

**Comment by Danielhiversen** [comment]
Duplicate of #29

**Comment by Danielhiversen** [comment]
As long as the gateway reports an empty model name the device isn't supported of the current gateway firmware. Please wait for the next firmware release of xiaomi.
