### ISSUE TITLE
Unsupported device found

### ISSUE THREAD

**Issue by winlio** [Danielhiversen/PyXiaomiGateway#50]
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'sid': '158d0002114c98', 'data': '{"voltage":3600,"channel_0":"off"}', 'short_id': 63774, 'cmd': 'read_ack', 'model': ''}

**Comment by syssi** [comment]
Do you use a recent gateway firmware? If not: Please update. If yes: You must wait for a new gateway firmware. As long as the field "model" is empty your device isn't supported of the current gateway firmware.

**Comment by xain** [comment]
I also see the error. I use a recent gateway firmware.

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'data': '{"voltage":3600,"channel_0":"on"}', 'short_id': 42290, 'model': '', 'cmd': 'read_ack', 'sid': '158d00021128cb'}

I believe it is [this switch](https://item.jd.com/4607278.html)
