### ISSUE TITLE
Xiaomi Aqara Wall Switch not detected correctly

### ISSUE THREAD

**Issue by dannys-pp** [Danielhiversen/PyXiaomiGateway#54]
I installed a Xiaomi Aqara ZigBee Wall Switch (single).
Here's the product:
[](https://www.gearbest.com/alarm-systems/pp_625774.html)

It works fine with the Xiaomi ios app.
However, it's not detected in hass.

Here's the error from the log file:

> 2018-02-19 21:02:02 ERROR (Thread-2) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'sid': '158d0001f2b07e', 'data': '{"voltage":3600,"channel_0":"on"}', 'model': '', 'cmd': 'read_ack', 'short_id': 27328}

**Comment by syssi** [comment]
The next version of the library will report this more precise error:

https://github.com/Danielhiversen/PyXiaomiGateway/pull/52/files

Do you use a recent gateway firmware? If yes, you've to wait unfortunately. The gateway provides two APIs. The sencond one (local network protocol) doesn't support new hardware occasionally.

**Comment by dannys-pp** [comment]
This morning Xiaomi posted a new firmware for the gateway.
I tweaked the xiaomi_gateway to allow it to control the wall switch properly (as a workaround) and it's working great now.
Here's the code snippet:

>            model = resp["model"]
>            supported = False
>            # DANNYS - Workaround to support Xiaomi Aqara ZigBee Wall Switch
>             if model == 'ctrl_ln1.aq1':
>                  model = "ctrl_neutral1"
>                  _LOGGER.warn("Setting model type to [ctrl_neutral1]")**

The Wall Plug reports mode 'ctrl_ln1.aq1' and the code currently supports only 'ctrl_ln1'.
After changing the model to 'ctrl_neutral1' everything works perfect.
Thank you for writing this great code!
After that, I customized the entity in hass to use a pretty mdi icon and everything is tip top.

**Comment by syssi** [comment]
@Danielhiversen Could you merge #53? It will introduce the support for the new device models.

**Comment by syssi** [comment]
I will prepare a home assistant PR asap.

**Comment by dannys-pp** [comment]
Is this good enough?

2018-02-25 10:36:31 WARNING (Thread-11) [xiaomi_gateway] _send_cmd to 10.0.0.53 9898 >> b'{"cmd":"read","sid":"158d0001f2b07e"}'
2018-02-25 10:36:31 ERROR (Thread-11) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'sid': '158d0001f2b07e', 'short_id': 27328, 'model': 'ctrl_ln1.aq1', 'data': '{"voltage":3600,"channel_0":"on"}', 'cmd': 'read_ack'}


Danny

**Comment by syssi** [comment]
Perfect. Thanks!

**Comment by crhan** [comment]
@dannys-pp I don't have this firmware update yet. I still have the version of 1.4.1_151.0143 and cannot figure the 'LN wall switch double'

What is the newest firmware version?

**Comment by dannys-pp** [comment]
The latest version is 1.4.1_153.0143. You need to upgrade the firmware using the Xiaomi mobile app.
I don’t have experience with the double switch. You could play with the code, add debug messages and see if it works.

**Comment by syssi** [comment]
@crhan Please provide some debug output.

**Comment by crhan** [comment]
@dannys-pp @syssi Thank you for your reply. Today I finally got the `1.4.1_153.0143` firmware upgrade. And Now I can see the correct model name. But HA still report error. My HA version is 0.64

```
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'ctrl_ln2.aq1', 'sid': '158d00022a83d4', 'short_id': 29561, 'data': '{"voltage":3600}'}
```

**Comment by shin007** [comment]
@crhan 我也是，这个问题困难好久了，但是不知道怎么修改xiaomi.py文件

**Comment by shin007** [comment]
@dannys-pp  Hello, where to modify the code？  Where is the path of the file？
       model = resp["model"]
       supported = False
       # DANNYS - Workaround to support Xiaomi Aqara ZigBee Wall Switch
        if model == 'ctrl_ln1.aq1':
             model = "ctrl_neutral1"
             _LOGGER.warn("Setting model type to [ctrl_neutral1]")**

**Comment by syssi** [comment]
The next release of HA (0.65) supports the new devices.

**Comment by shin007** [comment]
@syssi thank you

**Comment by shin007** [comment]
@syssi But when is the version 0.65 released?

**Comment by syssi** [comment]
The release cycle of HA is 14 days.

**Comment by syssi** [comment]
You could use the development branch of HA if you are using python>=3.5.

**Comment by shin007** [comment]
@syssi How do I use the developer branch and what plug-ins do I need to install? I don't know what the file path that needs to be modified,I can use PUTTY to connect the Hassio

**Comment by syssi** [comment]
If you use hassio you cannot use the development branch unfortunately. A official release of HA is required.

**Comment by shin007** [comment]
@syssi Can the IDE plug-in be modified?

**Comment by shin007** [comment]
@syssi I can't upload a screenshot, the IDE plug-in is here: https://github.com/hassio-addons/repository

**Comment by shin007** [comment]
@syssi this:  https://github.com/hassio-addons/addon-ide

**Comment by syssi** [comment]
No. The IDE is for YAML files (configurations).

**Comment by shin007** [comment]
@syssi Well, thank you very much for your answer
