### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by bardatwork** [Danielhiversen/PyXiaomiGateway#55]
error in log saying:

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': '', 'sid': '158d0001e05d64', 'short_id': 15028, 'data': '{"voltage":3409}'}

**Comment by syssi** [comment]
Please update your gateway firmware.

**Comment by bardatwork** [comment]
Hi,

Gateway is at latest firmware 1.4.1_151.0143. 

Only started thread coz error log told me to do so. 

On 26 Feb 2018, at 1:28 PM, Sebastian Muszynski <notifications@github.com> wrote:

Please update your gateway firmware.

**Comment by syssi** [comment]
The error messages was improved recently. Please update the library / home assistant, too. ;-)

**Comment by bardatwork** [comment]
ok, thank you
