### ISSUE TITLE
Upgrades PyXiaomiGateway 0.8.2

### ISSUE THREAD

**Issue by mylinc** [Danielhiversen/PyXiaomiGateway#57]
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'ctrl_ln2.aq1', 'sid': '158d0001f2472a', 'short_id': 39745, 'data': '{"voltage":3600}'}
2:47 deps/lib/python3.6/site-packages/xiaomi_gateway/__init__.py (ERROR)

Home Assistant  0.64.1

My operation:
   pip3 install -U https://github.com/Danielhiversen/PyXiaomiGateway/archive/0.8.2.zip

**Comment by mylinc** [comment]
'model': 'ctrl_ln2.aq1'

**Comment by syssi** [comment]
The next release (0.65) of homeassistant will support the device.

**Comment by syssi** [comment]
A upgrade by "pip3 install -u" won't work. Homeassistant downgrades the depency on startup. You've to start homeassistant by `bin/hass --skip-pip` to avoid the downgrade.
