### ISSUE TITLE
Xiaomi Aqara Smart Door Lock is unsupported device 

### ISSUE THREAD

**Issue by itanczos** [Danielhiversen/PyXiaomiGateway#58]
LOG entry:
2018-03-01 21:56:50 ERROR (SyncWorker_14) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'lock.aq1', 'sid': '158d000222cc3f', 'short_id': 19500, 'data': '{"voltage":3365}'}

Item link: [https://www.gearbest.com/home-smart-improvements/pp_1434928.html](url)

**Comment by syssi** [comment]
Could you provide some response example? I would like to implement the device.

**Comment by syssi** [comment]
I tought about it. The provided response above is the `read_ack` response already. It provides just the voltage (battery level) of the device. This isn't enough. The data field must provide a state or some other informations about the device. I assume the device isn't supported properly of the gateway firmware so far.

**Comment by elmexdechileen** [comment]
Ah, I actually posted the same question. I think we have to wait for the API to support it.

**Comment by monster1025** [comment]
Here is some "data" examples (sended by lock as "events"):
```
Publishing message to topic home/lock.aq1/158d000222****/fing_verified: 65536
Publishing message to topic home/lock.aq1/158d000222****/fing_verified: 65537
Publishing message to topic home/lock.aq1/158d000222****/psw_verified: 131074
Publishing message to topic home/lock.aq1/158d000222****/verified_wrong: 3
Publishing message to topic home/lock.aq1/158d000222****/verified_wrong: 4
Publishing message to topic home/lock.aq1/158d000222****/verified_wrong: 5
Publishing message to topic home/lock.aq1/158d000222****/fing_verified: 65537
Publishing message to topic home/lock.aq1/158d000222****/card_verified: 196608
```
It responds on 'read' command only voltage value.
