### ISSUE TITLE
Unsupported device found!

### ISSUE THREAD

**Issue by qwte** [Danielhiversen/PyXiaomiGateway#60]
ERROR (SyncWorker_9) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'ctrl_ln2.aq1', 'sid': '158d00022b51f6', 'short_id': 2528, 'data': '{"voltage":3600}'}

**Comment by syssi** [comment]
Duplicate of #59.
