### ISSUE TITLE
Xiaomi Wall Scoket 

### ISSUE THREAD

**Issue by linxingyulxy** [Danielhiversen/PyXiaomiGateway#61]
Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'sid': '158d0002251efb', 'model': 'ctrl_86plug.aq1', 'data': '{"voltage":3600,"status":"on","inuse":"1","power_consumed":"83","load_power":"34.84"}', 'short_id': 14419}

![_20180304200406](https://user-images.githubusercontent.com/3366397/36945343-4cc15f56-1fe7-11e8-8fac-bad9cce93924.png)

Is this support at HA 0.65?

**Comment by Danielhiversen** [comment]
Yes, this should be supported from version 0.65 of HA
