### ISSUE TITLE
Xiaomi Aqara Wall Socket not supported

### ISSUE THREAD

**Issue by rainaih** [Danielhiversen/PyXiaomiGateway#62]
Please help.

Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'ctrl_86plug.aq1', 'sid': '158d00022521c0', 'short_id': 42050, 'data': '{"voltage":3600,"status":"on","inuse":"1","power_consumed":"2789","load_power":"0.37"}'}
![image](https://user-images.githubusercontent.com/37094145/37017470-b8477fca-214b-11e8-8be6-73eca6efeb81.png)

**Comment by syssi** [comment]
The device will be supported of the next Home Assistant release (0.65).
