### ISSUE TITLE
 "Invalid key" after some requests

### ISSUE THREAD

**Issue by WagnerBeccard** [Danielhiversen/PyXiaomiGateway#73]
When im Wrong here fell free to close or delete or put me in the right direction. 
Also please rename it, my creativity is at the end 

just seted up the Gateway with Home Assistant, and well.. It refuses to work propertly. 
seted up one button (lumi.sensor_switch.v2)
Also the host option HAVE to be configured - otherwise the gatwav wont be found

For example the Lux sensor on the gateway. 
https://image.ibb.co/d4DgQd/Lux2.jpg
(it got data from 20:34 until 21:09 rest of the time.. dead?)

The Button just works for 25- 30 secconds after the first click.
You can click rapidly for minutes, but when you stop, its not reacting anymore
so click again after that time period and nothing happens. ( not even invalid key) 

Turning the Light on the Gateway on and off is poison - instant error with invalid key

Restarting HA resetting this problem 

I'ts maybe the hardware, not shure.
hw_ver: MW300 - model Lumi.gatewav.v3 
just updated to 1.4.1_155 - didnt changed behaviur
mcu_fw 0143

The app says 
version code 187 
Plugin version 2.56.3

Home Assistant
0.69.0

Logs:
https://hastebin.com/nivazicifi.rb
https://hastebin.com/uconoqeden.hs
https://hastebin.com/ohiciribuq.coffeescript
https://hastebin.com/leguhoyava.scala

**Comment by syssi** [comment]
Your network doesn't handle multicast traffic properly. Try to replace your accesspoint, design your network as simple as possible for testing and try to avoid virtualization.
