### ISSUE TITLE
 Unsupported device found --aqara cube

### ISSUE THREAD

**Issue by x01673** [Danielhiversen/PyXiaomiGateway#74]
I just bought a aqara cube,and it seems that it is not supported in the latest hassio 0.90.

here is the log info: 

 Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'sensor_cube.aqgl01', 'sid': '158d0002310c34', 'short_id': 57840, 'data': '{"voltage":3005}'}

Could you please check this issue? 
Thanks

**Comment by syssi** [comment]
This is already fixed. The device will be supported in HA 0.70.
