### ISSUE TITLE
Unsupported device Xiaomi Aqara cube

### ISSUE THREAD

**Issue by tatdatpham** [Danielhiversen/PyXiaomiGateway#75]
Hi @Danielhiversen ,

Im ussing HA v.0.69 in raspbian. I bought new device called [xiaomi aqara cube ](https://www.aliexpress.com/item/Xiaomi-Aqara-Mi-Magic-Cube-Controller-Zigbee-Version-Support-Upgrade-Gateway-Smart-Home-Mijia-Device-Wireless/32871531067.html?spm=2114.search0104.3.2.6d7d1257uzlAII&ws_ab_test=searchweb0_0,searchweb201602_1_10152_10151_10065_10344_10068_10547_10342_10343_10340_10548_10341_10696_10084_10083_10618_10307_10059_308_100031_10103_10624_10623_10622_10621_10620_10814_10815,searchweb201603_55,ppcSwitch_3&algo_expid=7fb15d46-b10d-4562-ada1-30fd9f3a6bad-0&algo_pvid=7fb15d46-b10d-4562-ada1-30fd9f3a6bad&priceBeautifyAB=0) .
When i start HA, i got error : 

`May 22 13:18:06 raspberrypi hass[2393]: 2018-05-22 13:18:06 ERROR (Thread-4) [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'data': '{"voltage":2955}', 'short_id': 11544, 'model': 'sensor_cube.aqgl01', 'sid': '158d0002481496', 'cmd': 'read_ack'}
`
I hope you will be update code for support this device. I think my device is xiaomi cube version 2 :D

**Comment by tatdatpham** [comment]
Sorry, just found info [https://github.com/Danielhiversen/PyXiaomiGateway/issues/67](https://github.com/Danielhiversen/PyXiaomiGateway/issues/67)

**Comment by syssi** [comment]
This is already fixed. The device will be supported in HA 0.70.
