### ISSUE TITLE
Unsupported device found——Aqara Wireless Switch (Double)

### ISSUE THREAD

**Issue by siliscar** [Danielhiversen/PyXiaomiGateway#82]
{'model': 'sensor_86sw2', 'params': [{'battery_voltage': 3125}], 'sid': '158d0002338de6', 'cmd': 'read_rsp'}

Error message's above when HA's component said that Aqara Wireless Switch (Double) is  in "xiaomi_aqara" 's Supported Device lists.

**Comment by siliscar** [comment]
My HA's version is  0.70.1

**Comment by syssi** [comment]
Will be fixed with #113 and a firmware update of your gateway.
