### ISSUE TITLE
Unsupported device: Aqara Wireless Remote Switch (New version)

### ISSUE THREAD

**Issue by hktomy** [Danielhiversen/PyXiaomiGateway#88]
Hi,

I've recently bought the latest version of Aqara Wireless Remote Switch (Double) and got the following error:

 [xiaomi_gateway] Unsupported device found! Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b286acn01', 'sid': '158d000282a212', 'short_id': 40171, 'data': '{"voltage":3055}'}

**Comment by martininio** [comment]
Also received the Aqara Wireless Remote Switch (Double Rocker) and got the following error when added the device to home assistant: 

Please create an issue at https://github.com/Danielhiversen/PyXiaomiGateway/issues and provide the following data: {'cmd': 'read_ack', 'model': 'remote.b286acn01', 'sid': '158d00027c1f6a', 'short_id': 51499, 'data': '{"voltage":3155}'

**Comment by martininio** [comment]
the model written on the box: WXKG02LM

**Comment by martininio** [comment]
I applied the following workaround to get my switches (model 'remote.b286acn01') working:
1.  Download the file: https://github.com/Danielhiversen/PyXiaomiGateway/blob/master/xiaomi_gateway/__init__.py

2. Copy the file to home assistant location  \\HOMEASSISTANTIP\config\xaiomi_gateway
note: if xiaomi_gateway folder doesn't exist, just create it.

3. Download the file:
https://github.com/home-assistant/home-assistant/raw/master/homeassistant/components/binary_sensor/xiaomi_aqara.py

4. Copy this file to:  \\HOMEASSISTANTIP\config\custom_components\binary_sensor
note: if  \custom_components\binary_sensor folders do not exist, just create them.

5. Open the file __init__.py (with a text editor like Notepad++)
6.  add 'remote.b286acn01', to line 247

7. Open the file xaiomi_aqara.py  (with a text editor like Notepad++)
8. add 'remote.b286acn01' to line 53

9. Reboot Home Assistant. Now you will find them as a binary sensor entity ID

**Comment by domwonghk** [comment]
single and double click are all right but "long_click_press" can not be used upon automation
