### ISSUE TITLE
Unsupported device - Aqara wireless button WXKG11LM

### ISSUE THREAD

**Issue by MrSMlT** [Danielhiversen/PyXiaomiGateway#97]
Found an unsupported device with the following data: {'cmd': 'read_ack', 'model': 'remote.b1acn01', 'sid': '158d0001ef5f63', 'short_id': 58691, 'data': '{"voltage":3095}'}

It's a square-shaped Aqara wireless switch/button (WXKG11LM). So I modified the two files below to include this new model 'remote.b1acn01'. It's now recognised correctly.

/usr/lib/python3.6/site-packages/xiaomi_gateway/__init__.py

/usr/lib/python3.6/site-packages/homeassistant/components/binary_sensor/xiaomi_aqara.py

**Comment by martininio** [comment]
Thanks to MrSMIT i applied the following workaround to get my switches (model 'remote.b286acn01') working:

1.Download the file: https://github.com/Danielhiversen/PyXiaomiGateway/blob/master/xiaomi_gateway/__init__.py

2.Copy the file to home assistant location \\HOMEASSISTANTIP\config\xaiomi_gateway
 note: if xiaomi_gateway folder doesn't exist, just create it.

3.Download the file:
https://github.com/home-assistant/home-assistant/raw/master/homeassistant/components/binary_sensor/xiaomi_aqara.py

4.Copy this file to: \HOMEASSISTANTIP\config\custom_components\binary_sensor
 note: if \custom_components\binary_sensor folders do not exist, just create them.

5.Open the file "init.py" (with a text editor like Notepad++)

6.add 'remote.b286acn01', to line 247

7.Open the file "xaiomi_aqara.py" (with a text editor like Notepad++)

8.add 'remote.b286acn01' to line 53

9.Reboot Home Assistant. Now you will find your switch as a binary_sensor entity ID

**Comment by domwonghk** [comment]
Although the device can be found but no response state upon automation

**Comment by jussbba** [comment]
Hello MrSMIT,

I have exactly same problem as you had. Could you tell me which lines you edited? 
Thank you in advance.

**Comment by fleshinchair** [comment]
> Thanks to MrSMIT i applied the following workaround to get my switches (model 'remote.b286acn01') working:
> 
> 1.Download the file: https://github.com/Danielhiversen/PyXiaomiGateway/blob/master/xiaomi_gateway/__init__.py
> 
> 2.Copy the file to home assistant location \\HOMEASSISTANTIP\config\xaiomi_gateway
> note: if xiaomi_gateway folder doesn't exist, just create it.
> 
> 3.Download the file:
> https://github.com/home-assistant/home-assistant/raw/master/homeassistant/components/binary_sensor/xiaomi_aqara.py
> 
> 4.Copy this file to: \\HOMEASSISTANTIP\config\custom_components\binary_sensor
> note: if \custom_components\binary_sensor folders do not exist, just create them.
> 
> 5.Open the file "init.py" (with a text editor like Notepad++)
> 
> 6.add 'remote.b286acn01', to line 247
> 
> 7.Open the file "xaiomi_aqara.py" (with a text editor like Notepad++)
> 
> 8.add 'remote.b286acn01' to line 53
> 
> 9.Reboot Home Assistant. Now you will find your switch as a binary_sensor entity ID

Hi there, thanks for sharing these instructions, I tried it but couldnt get it to work - does the xiaomi_gateway folder definitely go in the config folder or is it maybe meant to go in the config/custom_components folder?
and does the init.py file have to have the underscores removed (its downloaded as _init_.py )

**Comment by syssi** [comment]
Fixed by #108 and will be introduced into Home Assistant soon.
