### ISSUE TITLE
Unsupported Aqara Vibration Sensor - DJT11LM

### ISSUE THREAD

**Issue by vorostamas** [Danielhiversen/PyXiaomiGateway#98]
Hi,
I found an unsupported device with the following data:
`{'cmd': 'read_ack', 'model': 'vibration', 'sid': '158d0002a240fc', 'short_id': 45948, 'data': '{"voltage":3175}'}`

It's the new Aqara Vibration Sensor with the model number DJT11LM.

**Comment by bobnwk** [comment]
{'sid': '158d0002a9219d', 'data': '{"voltage":3095}', 'short_id': 38595, 'model': 'vibration', 'cmd': 'read_ack'}

**Comment by pustefix8965** [comment]
{'cmd': 'read_ack', 'model': 'vibration', 'sid': '158d0002a52381', 'short_id': 56459, 'data': '{"voltage":3085}'}
DJT11LM

**Comment by SelcouthGuy** [comment]
Same here.
{'data': '{"voltage":3105}', 'sid': '158d0002a91f9c', 'short_id': 47453, 'model': 'vibration', 'cmd': 'read_ack'}

**Comment by syssi** [comment]
This library already supports the vibration sensor. Just the Home Assistant support isn't merged yet:

https://github.com/home-assistant/home-assistant/pull/16422
